version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: osemike/friendlymike:v1
    deploy:
      replicas: 7
      resources:
        limits:
          cpus: "0.07"
          memory: 70M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webtest
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "5050:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webtest
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/home/docker/data:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webtest
networks:
  webtest:
