version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: osemike/osedockerpractice:v1
    deploy:
      replicas: 7
      resources:
        limits:
          cpus: "0.07"
          memory: 70M
      restart_policy:
        condition: on-failure
    ports:
      - "5050:80"
    networks:
      - webtest
networks:
  webtest:
